name: "cheetah-config-creator"
version: "0.1.0"
description: "Создание ConfigMap из директории с конфигурацией"
ignoreFlags: false
platformCommand:
  - os: linux
    command: "$HELM_PLUGIN_DIR/cheetah-config-creator-linux"
  - os: darwin
    command: "$HELM_PLUGIN_DIR/cheetah-config-creator-macos"