name: "cheetah-config-creator"
version: "0.1.0"
description: "Создание ConfigMap из директории с конфигурацией"
ignoreFlags: false
#command: "echo The plugin is located in: \"$HELM_PLUGIN_DIR\" and its name is: \"$HELM_PLUGIN_NAME\""
platformCommand:
  - os: linux
    command: ./cheetah-config-creator-linux
  - os: darwin
#    command: "echo The plugin is located in: \"$HELM_PLUGIN_DIR\" and its name is: \"$HELM_PLUGIN_NAME\""
    command: ./cheetah-config-creator-macos